import { Product } from '../models/product.model';
import { Order, User } from '../models/index';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    nom: 'Kit Robot Voiture Intelligente 4WD',
    description: 'Kit robotique complet basé sur Arduino Uno avec capteurs ultrason, suivi de ligne et contrôle Bluetooth.',
    prix: 450,
    prixOriginal: 599,
    categorie: 'Électronique',
    sousCategorie: 'Robotique Arduino',
    marque: 'Arduino',
    image: './pi-supply-MY97RmOk1Fs-unsplash.webp',
    disponible: true,
    stock: 24,
    reduction: 25,
    badge: 'nouveau',
    note: 5,
    avis: 42
  },
  {
    id: 3,
    nom: 'Carte Officielle Arduino Uno R3',
    description: 'La carte microcontrôleur idéale pour débuter en électronique et réaliser vos projets de systèmes embarqués.',
    prix: 120,
    categorie: 'Électronique',
    sousCategorie: 'Composants',
    marque: 'Arduino',
    image: './mikhail-seleznev-_2r05WCBe4A-unsplash.webp',
    disponible: true,
    stock: 32,
    badge: undefined,
    note: 5,
    avis: 112
  },
  {
    id: 4,
    nom: 'Kit Capteurs IoT et Domotique',
    description: 'Ensemble de capteurs (température, humidité, gaz, présence) pour vos applications d\'objets connectés.',
    prix: 299,
    prixOriginal: 399,
    categorie: 'Électronique',
    sousCategorie: 'Robotique Arduino',
    marque: 'SmartTech',
    image: './lucian-alexe-yh0UtueiZ-I-unsplash.webp',
    disponible: true,
    stock: 18,
    badge: 'stock-bas',
    note: 4,
    avis: 29
  },
  {
    id: 5,
    nom: 'Amplificateur Hi-Fi Vintage Pro',
    description: 'Ampli stéréo haut de gamme au design rétro offrant une fidélité audio exceptionnelle et une puissance optimale.',
    prix: 2499,
    prixOriginal: 2999,
    categorie: 'Électronique',
    sousCategorie: 'Robotique Arduino',
    marque: 'VintageSound',
    image: './blaz-erzetic-J8e5IKXIEwY-unsplash.webp',
    disponible: true,
    stock: 5,
    badge: 'promo',
    note: 5,
    avis: 64
  },
  {
    id: 8,
    nom: 'Veste en Cuir Streetwear Casual',
    description: 'Veste moderne ajustée en cuir véritable, alliant confort thermique et style urbain élégant.',
    prix: 599,
    prixOriginal: 799,
    categorie: 'Électronique',
    sousCategorie: 'Robotique Arduino',
    marque: 'UrbainStyle',
    image: './aimg-il0_dFnxf9o-unsplash.webp',
    disponible: true,
    stock: 40,
    badge: 'nouveau',
    note: 4.5,
    avis: 89
  },
  {
    id: 9,
    nom: 'Kit Robot Intelligent Voiture 2WD',
    description: 'Sweat à capuche molletonné en coton biologique premium, coupe oversize pour un look décontracté.',
    prix: 299,
    categorie: 'Électronique',
    sousCategorie: 'Robotique Arduino',
    marque: 'StyleCo',
    image: './gabriel-vasiliu-F9Qjauv2C3g-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 10,
    nom: 'Sweat à Capuche Oversize "GLOOMY"',
    description: 'Améliorez votre style streetwear avec ce sweat à capuche (hoodie) épais et confortable. Conçu dans une coupe oversize moderne, il arbore une couleur vert sapin tendance',
    prix: 199,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './redicul-pict-T_8gjuk1Weo-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 11,
    nom: 'Adidas Originals Samba',
    description: "Les sneakers iconiques de chez Adidas Originals. Alliant le cuir blanc de qualité supérieure à des détails en daim beige et aux trois bandes emblématiques en noir (ou bleu marine foncé). Sa semelle en gomme rétro assure un confort optimal et une excellente adhérence. Un classique intemporel qui s'adapte à tous les styles.",
    prix: 800,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './chiara-guercio-4zWjLgMD0rs-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 12,
    nom: 'Sweat à Capuche Essentiel',
    description: "Le sweat à capuche basique et indispensable à avoir dans sa garde-robe. Conçu dans un tissu molletonné premium, ce hoodie couleur beige/sable offre une coupe décontractée et confortable. Équipé d'une poche kangourou et d'une capuche avec cordons de serrage ajustables. Parfait pour un style minimaliste et épuré",
    prix: 199,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './the-ian-ZCoqcrWp9GY-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 13,
    nom: 'Sweat à Capuche Oversize Graphique "CHANGE"',
    description: "Adoptez un look urbain et ultra-tendance avec ce hoodie noir oversize. Conçu dans un coton épais et confortable, il se démarque par ses graphismes minimalistes blancs et sa touche de texte orange contrastante à l'avant. Parfait pour les amateurs de streetwear à la recherche d'une pièce à la fois confortable et stylée.",
    prix: 249,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './bui-hoang-long-pqtT4HwHASo-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 14,
    nom: 'Espadrilles Tressées en Toile',
    description: "L'alliance parfaite entre confort estival et style authentique. Ces chaussures légères en toile se distinguent par leur semelle tressée façon espadrille et leurs détails de surpiqûres artisanales sur le contour. Disponibles en plusieurs coloris naturels (noir, beige, kaki, rose poudré), elles sont idéales pour compléter une tenue décontractée et aérée.",
    prix: 250,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './nuki-chikhladze-UFyRPNfHjrQ-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 15,
    nom: 'T-shirt Oversize Adidas Originals',
    description: "Le t-shirt basique indispensable avec une touche sportswear iconique. Ce t-shirt blanc Adidas Originals propose une coupe oversize décontractée et un col rond classique. Arborant fièrement le logo Trèfle brodé au centre de la poitrine, il offre un confort inégalé grâce à sa conception en coton doux. Un indispensable pour un style sportswear quotidien.",
    prix: 249,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './idriss-orfeo-kFyE5ZSLiTU-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 16,
    nom: 'weat à capuche oversize',
    description: "Sweat-shirt à capuche pour femme, coupe oversize confortable avec des manches tombantes. Conçu dans un tissu épais idéal pour la saison automne-hiver.",
    prix: 249,
    categorie: 'mode',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './oladimeji-odunsi-aNj8Hvbrss8-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 17,
    nom: 'Fauteuil Design Jaune Moutarde',
    description: " Meuble & Déco. Fauteuil rétro au style scandinave avec pieds en bois noir et revêtement en tissu jaune, idéal pour dynamiser un salon ou un coin lecture.",
    prix: 499,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './kam-idris-_HqHX3LBN18-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 18,
    nom: 'Canapé Droit 2 Places Blanc Crème',
    description:" Meuble & Déco. Canapé fixe confortable au style classique et intemporel, doté de coussins moelleux. Parfait pour les petits espaces et les salons chaleureux.",
    prix: 699,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './julia-RuCVvjuyNeQ-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 19,
    nom: 'Canapé Moderne 3 Places Gris Clair',
    description: " Meuble & Déco. Canapé contemporain en tissu gris avec pieds en bois clair, livré avec ses coussins décoratifs à motifs. Apporte une touche épurée et moderne à votre intérieur.",
    prix: 249,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './naomi-hebert-2dcYhvbHV-M-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 20,
    nom: 'Table Basse en Bois Massif Rustique',
    description: "  Meuble & Déco. Table basse de salon conçue à partir d'un plateau en bois brut aux bords naturels, montée sur des pieds en métal noir. Apporte une touche industrielle et chaleureuse.",
    prix: 199,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './trend-K9pU2u0Z5WU-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 21,
    nom: 'Miroir Rond Mural Cadre Noir',
    description: " Meuble & Déco. Grand miroir circulaire minimaliste avec un cadre fin en métal noir. Parfait pour agrandir visuellement l'espace au-dessus d'un buffet dans une entrée ou un salon.",
    prix: 299,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './spacejoy-h2_3dL9yLpU-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 22,
    nom: 'Buffet Enfilade en Cannage de Rotin',
    description: " Meuble & Déco. Buffet bas de style rétro chic avec portes habillées de cannage en rotin naturel et structure en bois clair. Offre un bel espace de rangement tout en restant ultra tendance.",
    prix: 400,
    categorie: 'maison',
    sousCategorie: 'vetement',
    marque: 'StyleCo',
    image: './spacejoy-YI2YkyaREHk-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 23,
    nom: 'Ballon de Football Américain en Cuir',
    description: " Sport & Fitness. Ballon ovale classique en cuir marron avec lacets blancs adhérents, idéal pour les entraînements et les matchs de football américain sur pelouse.",
    prix: 199,
    categorie: 'sport',
    sousCategorie: 'Footballe',
    marque: 'StyleCo',
    image: './dave-adamson--nATH0CrkMU-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 24,
    nom: 'Ballon de Football Classique',
    description: "  Sport & Fitness. Ballon de football de taille standard conçu pour offrir une excellente trajectoire et une résistance maximale sur pelouse naturelle ou synthétique. (Note : Bien que l'image montre le terrain et la cage, l'article vendu reste le ballon de foot).",
    prix: 249,
    categorie: 'sport',
    sousCategorie: 'Footballe',
    marque: 'StyleCo',
    image: './markus-spiske-KWQ2kQtxiKE-unsplash.webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
  {
    id: 25,
    nom: 'Ballon de Volley-ball',
    description: " Sport & Fitness. Ballon léger bicolore (jaune et blanc) adapté pour les sports collectifs en salle. Offre une excellente prise en main et un contact souple pour les passes et les smashs.",
    prix: 249,
    categorie: 'sport',
    sousCategorie: 'Footballe',
    marque: 'StyleCo',
    image: './estanislau-valmana-Y9sV1E-fd10-unsplash (1).webp',
    disponible: true,
    stock: 60,
    badge: undefined,
    note: 5,
    avis: 128
  },
];

export const ORDERS: Order[] = [
  {
    id: 1001,
    userId: 2,
    items: [
      { product: PRODUCTS[0], quantite: 1 },
      { product: PRODUCTS[2], quantite: 2 }
    ],
    total: 1897,
    statut: 'livree',
    date: new Date('2024-01-15'),
    adresse: {
      nom: 'Alaoui', prenom: 'Sana',
      adresse: '123 rue des Orangers',
      ville: 'Casablanca', codePostal: '20000',
      telephone: '0600000000', email: 'sana@example.com'
    }
  },
  {
    id: 1002,
    userId: 3,
    items: [{ product: PRODUCTS[1], quantite: 1 }],
    total: 1299,
    statut: 'livraison',
    date: new Date('2024-02-10'),
    adresse: {
      nom: 'Benali', prenom: 'Karim',
      adresse: '45 avenue Hassan II',
      ville: 'Rabat', codePostal: '10000',
      telephone: '0611111111', email: 'karim@example.com'
    }
  },
  {
    id: 1003,
    userId: 2,
    items: [{ product: PRODUCTS[3], quantite: 1 }, { product: PRODUCTS[4], quantite: 1 }],
    total: 1098,
    statut: 'confirmee',
    date: new Date('2024-03-05'),
    adresse: {
      nom: 'Alaoui', prenom: 'Sana',
      adresse: '123 rue des Orangers',
      ville: 'Casablanca', codePostal: '20000',
      telephone: '0600000000', email: 'sana@example.com'
    }
  }
];

export const USERS: User[] = [
  {
    id: 1,
    nom: 'Admin',
    prenom: 'ShopNow',
    email: 'admin@shopnow.ma',
    role: 'admin',
    dateInscription: new Date('2023-01-01'),
    actif: true
  },
  {
    id: 2,
    nom: 'Alaoui',
    prenom: 'Sana',
    email: 'sana@example.com',
    role: 'user',
    dateInscription: new Date('2023-06-15'),
    actif: true
  },
  {
    id: 3,
    nom: 'Benali',
    prenom: 'Karim',
    email: 'karim@example.com',
    role: 'user',
    dateInscription: new Date('2023-09-20'),
    actif: true
  },
  {
    id: 4,
    nom: 'Idrissi',
    prenom: 'Fatima',
    email: 'fatima@example.com',
    role: 'user',
    dateInscription: new Date('2024-01-10'),
    actif: false
  }
];